In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r'C:\Users\jackm\Documents\Data Analytics\CW\world-happiness (1)\2017.csv')

In [2]:
df2 = pd.read_csv(r'C:\Users\jackm\Documents\Data Analytics\CW\undata-country-profiles\country_profile_variables.csv')

In [3]:
df.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [4]:
df2.head()

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,96.9,13,34,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99

In [5]:
#Rename column of country in df2 to match df
df_renamed = df2.rename(columns = {'country': 'Country'})

In [6]:
df_renamed

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,96.9,13,34,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,-99,-99,-99.0,-99,...,9,89,41.6,~0.0/1.6,-99,26,-99,-99,-99,-99
225,Western Sahara,NorthernAfrica,266000,553,2.1,110.1,-99,-99,-99.0,-99,...,-99,49,2.7,-99,-99,-99,-99,-99,-99,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688,-28.1,1106.4,14.7,...,25.1,298,1,22.7/0.9,668,12,72.0/46.5,92.5/34.1,2.99,-99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255,2.9,1311.1,8.2,...,21,88,65.6,4.5/0.3,374,26,85.6/51.3,55.6/35.7,3.96,-99
228,Zimbabwe,EasternAfrica,390757,16530,42.7,95.0,13893,1.1,890.4,13,...,16.4,89,37.2,12.0/0.8,482,30,97.0/67.3,49.3/30.8,6,-99

In [7]:
#Strip Whitespace in Country names to ensure they match
df['Country'] = df['Country'].str.replace(" ", "")
df['Country'] = df['Country'].str.upper() 
df.to_csv(r'C:\Users\jackm\Documents\Data Analytics\CW\TrimHappiness.csv', index = False)

df_renamed['Country'] = df_renamed['Country'].str.replace(" ", "")
df_renamed['Country'] = df_renamed['Country'].str.upper() 
df_renamed.to_csv(r'C:\Users\jackm\Documents\Data Analytics\CW\TrimStats.csv', index = False)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\jackm\\Documents\\Data Analytics\\CW\\TrimStats.csv'

In [8]:
df_merged=pd.merge(df, df_renamed, left_on='Country', right_on='Country')

In [9]:
df_merged

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,NORWAY,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,...,96.8,64,33.2,47.6/9.2,8204,233,100.0/100.0,98.0/98.3,-99,-99
1,DENMARK,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,...,96.3,47,14.4,33.5/5.9,666,119,100.0/100.0,99.6/99.6,-99,-99
2,ICELAND,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,...,98.2,27,0.5,2.0/6.1,284,952,100.0/100.0,98.7/100.0,-99,-99
3,SWITZERLAND,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,...,88,74,31.6,35.3/4.3,552,126,100.0/100.0,99.9/99.8,-99,-99
4,FINLAND,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,...,92.7,36,73.1,47.3/8.6,757,257,100.0/100.0,99.4/88.0,-99,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,GUINEA,149,3.507,3.584428,3.429572,0.244550,0.791245,0.194129,0.348588,0.264815,...,4.7,185,26,2.4/0.2,113,12,92.7/67.4,34.1/11.8,8.65,-99
133,TOGO,150,3.495,3.594038,3.395962,0.305445,0.431883,0.247106,0.380426,0.196896,...,7.1,80,3.8,2.6/0.4,111,20,91.4/44.2,24.7/2.9,5.51,-99
134,RWANDA,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,...,18,62,19.2,0.8/0.1,84,8,86.6/71.9,58.5/62.9,13.67,-99
135,BURUNDI,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,...,4.9,61,10.6,0.4/~0.0,56,6,91.1/73.8,43.8/48.6,11.91,-99
136,CENTRALAFRICANREPUBLIC,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,...,4.6,60,35.6,0.3/0.1,19,5,89.6/54.4,43.6/7.2,32.25,-99

In [10]:
df_merged.to_csv(r'C:\Users\jackm\Documents\Data Analytics\CW\2017Merge.csv', index = False)

In [11]:
#outerjoin to determine missing values 
df_missing = pd.merge(df, df_renamed, on ='Country', how='left')

In [12]:
#Check how many countries are missing = 18 missing counties
df_missing.isnull().sum()

Country                                                        0
Happiness.Rank                                                 0
Happiness.Score                                                0
Whisker.high                                                   0
Whisker.low                                                    0
                                                              ..
Energy production, primary (Petajoules)                       18
Energy supply per capita (Gigajoules)                         18
Pop. using improved drinking water (urban/rural, %)           18
Pop. using improved sanitation facilities (urban/rural, %)    18
Net Official Development Assist. received (% of GNI)          18
Length: 61, dtype: int64

In [13]:
#Create a new dataframe of all null values, provides list of the missing countries and shows difference in names that explains why

null_data = df_missing[df_missing.isnull().any(axis=1)]

In [14]:
print(null_data)

                    Country  Happiness.Rank  Happiness.Score  Whisker.high  \
13             UNITEDSTATES              14            6.993      7.074657
32    TAIWANPROVINCEOFCHINA              33            6.422      6.494596
48                   RUSSIA              49            5.963      6.030275
54               SOUTHKOREA              55            5.838      5.922559
55                  MOLDOVA              56            5.838      5.908371
57                  BOLIVIA              58            5.823      5.903977
60              NORTHCYPRUS              61            5.810      5.897366
70     HONGKONGS.A.R.,CHINA              71            5.472      5.549594
77                   KOSOVO              78            5.279      5.364848
81                VENEZUELA              82            5.250      5.370032
91                MACEDONIA              92            5.175      5.272173
102  PALESTINIANTERRITORIES             103            4.775      4.881848
107                    IRAN             108            4.692      4.798225
123      CONGO(BRAZZAVILLE)             124            4.291      4.410054
125         CONGO(KINSHASA)             126            4.280      4.357811
127              IVORYCOAST             128            4.180      4.275183
151                   SYRIA             152            3.462      3.663669
152                TANZANIA             153            3.349      3.461430

     Whisker.low  Economy..GDP.per.Capita.    Family  \
13      6.911343                  1.546259  1.419921
32      6.349404                  1.433627  1.384565
48      5.895725                  1.281778  1.469282
54      5.753441                  1.401678  1.128274
55      5.767629                  0.728871  1.251826
57      5.742023                  0.833757  1.227619
60      5.722633                  1.346911  1.186303
70      5.394406                  1.551675  1.262791
77      5.193152                  0.951484  1.137854
81      5.129968                  1.128431  1.431338
91      5.077828                  1.064578  1.207893
102     4.668152                  0.716249  1.155647
107     4.585775                  1.156873  0.711551
123     4.171946                  0.808964  0.832044
125     4.202190                  0.092102  1.229023
127     4.084817                  0.603049  0.904780
151     3.260331                  0.777153  0.396103
152     3.236570                  0.511136  1.041990

     Health..Life.Expectancy.   Freedom  Generosity  ...  \
13                   0.774287  0.505741    0.392579  ...
32                   0.793984  0.361467    0.258360  ...
48                   0.547349  0.373783    0.052264  ...
54                   0.900214  0.257922    0.206674  ...
55                   0.589465  0.240729    0.208779  ...
57                   0.473630  0.558733    0.225561  ...
60                   0.834647  0.471204    0.266846  ...
70                   0.943062  0.490969    0.374466  ...
77                   0.541452  0.260288    0.319931  ...
81                   0.617144  0.153997    0.065020  ...
91                   0.644948  0.325906    0.253761  ...
102                  0.565667  0.254711    0.114173  ...
107                  0.639333  0.249323    0.387243  ...
123                  0.289957  0.435026    0.120852  ...
125                  0.191407  0.235961    0.246456  ...
127                  0.048642  0.447706    0.201237  ...
151                  0.500533  0.081539    0.493664  ...
152                  0.364509  0.390018    0.354256  ...

     Mobile-cellular subscriptions (per 100 inhabitants).1  \
13                                                 NaN
32                                                 NaN
48                                                 NaN
54                                                 NaN
55                                                 NaN
57                                                 NaN
60                                                 NaN
70                                                 NaN
77                                                 NaN
81                                                 NaN
91                                                 NaN
102                                                NaN
107                                                NaN
123                                                NaN
125                                                NaN
127                                                NaN
151                                                NaN
152                                                NaN

     Individuals using the Internet (per 100 inhabitants)  \
13                                                 NaN
32                                                 NaN
48                                                 NaN
54                                                 NaN
55                                                 NaN
57                                                 NaN
60                                                 NaN
70                                                 NaN
77                                                 NaN
81                                                 NaN
91                                                 NaN
102                                                NaN
107                                                NaN
123                                                NaN
125                                                NaN
127                                                NaN
151                                                NaN
152                                                NaN

    Threatened species (number) Forested area (% of land area)  \
13                          NaN                            NaN
32                          NaN                            NaN
48                          NaN                            NaN
54                          NaN                            NaN
55                          NaN                            NaN
57                          NaN                            NaN
60                          NaN                            NaN
70                          NaN                            NaN
77                          NaN                            NaN
81                          NaN                            NaN
91                          NaN                            NaN
102                         NaN                            NaN
107                         NaN                            NaN
123                         NaN                            NaN
125                         NaN                            NaN
127                         NaN                            NaN
151                         NaN                            NaN
152                         NaN                            NaN

     CO2 emission estimates (million tons/tons per capita)  \
13                                                 NaN
32                                                 NaN
48                                                 NaN
54                                                 NaN
55                                                 NaN
57                                                 NaN
60                                                 NaN
70                                                 NaN
77                                                 NaN
81                                                 NaN
91                                                 NaN
102                                                NaN
107                                                NaN
123                                                NaN
125                                                NaN
127                                                NaN
151                                                NaN
152                                                NaN

     Energy production, primary (Petajoules)  \
13                                       NaN
32                                       NaN
48                                       NaN
54                                       NaN
55                                       NaN
57                                       NaN
60                                       NaN
70                                       NaN
77                                       NaN
81                                       NaN
91                                       NaN
102                                      NaN
107                                      NaN
123                                      NaN
125                                      NaN
127                                      NaN
151                                      NaN
152                                      NaN

     Energy supply per capita (Gigajoules)  \
13                                     NaN
32                                     NaN
48                                     NaN
54                                     NaN
55                                     NaN
57                                     NaN
60                                     NaN
70                                     NaN
77                                     NaN
81                                     NaN
91                                     NaN
102                                    NaN
107                                    NaN
123                                    NaN
125                                    NaN
127                                    NaN
151                                    NaN
152                                    NaN

     Pop. using improved drinking water (urban/rural, %)  \
13                                                 NaN
32                                                 NaN
48                                                 NaN
54                                                 NaN
55                                                 NaN
57                                                 NaN
60                                                 NaN
70                                                 NaN
77                                                 NaN
81                                                 NaN
91                                                 NaN
102                                                NaN
107                                                NaN
123                                                NaN
125                                                NaN
127                                                NaN
151                                                NaN
152                                                NaN

    Pop. using improved sanitation facilities (urban/rural, %)  \
13                                                 NaN
32                                                 NaN
48                                                 NaN
54                                                 NaN
55                                                 NaN
57                                                 NaN
60                                                 NaN
70                                                 NaN
77                                                 NaN
81                                                 NaN
91                                                 NaN
102                                                NaN
107                                                NaN
123                                                NaN
125                                                NaN
127                                                NaN
151                                                NaN
152                                                NaN

     Net Official Development Assist. received (% of GNI)
13                                                 NaN
32                                                 NaN
48                                                 NaN
54                                                 NaN
55                                                 NaN
57                                                 NaN
60                                                 NaN
70                                                 NaN
77                                                 NaN
81                                                 NaN
91                                                 NaN
102                                                NaN
107                                                NaN
123                                                NaN
125                                                NaN
127                                                NaN
151                                                NaN
152                                                NaN

[18 rows x 61 columns]

In [15]:
#check for strings containing country names to determine why join didn't occur
df_renamed[df_renamed['Country'].str.contains("UNITEDSTATES")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
217,UNITEDSTATESOFAMERICA,NorthernAmerica,9833517,324460,35.5,98.0,18036648,2.6,56053.8,1,...,74.6,1513,33.9,5254.3/16.2,83887,289,99.4/98.2,100.0/100.0,-99,-99
218,UNITEDSTATESVIRGINISLANDS,Caribbean,347,105,299.7,91.1,-99,-99,-99.0,-99,...,54.8,58,50.6,-99,-99,-99,100.0/100.0,96.4/96.4,-99,-99

In [16]:
#change to united states
df_renamed['Country'] = df_renamed['Country'].replace(['UNITEDSTATESOFAMERICA'], ['UNITEDSTATES'])

In [17]:
#check for Taiwan, not included as it is counted as province of China in National Statistics data set
df_renamed[df_renamed['Country'].str.contains("TAIW")]

Empty DataFrame
Columns: [Country, Region, Surface area (km2), Population in thousands (2017), Population density (per km2, 2017), Sex ratio (m per 100 f, 2017), GDP: Gross domestic product (million current US$), GDP growth rate (annual %, const. 2005 prices), GDP per capita (current US$), Economy: Agriculture (% of GVA), Economy: Industry (% of GVA), Economy: Services and other activity (% of GVA), Employment: Agriculture (% of employed), Employment: Industry (% of employed), Employment: Services (% of employed), Unemployment (% of labour force), Labour force participation (female/male pop. %), Agricultural production index (2004-2006=100), Food production index (2004-2006=100), International trade: Exports (million US$), International trade: Imports (million US$), International trade: Balance (million US$), Balance of payments, current account (million US$), Population growth rate (average annual %), Urban population (% of total population), Urban population growth rate (average annual %), Fertility rate, total (live births per woman), Life expectancy at birth (females/males, years), Population age distribution (0-14 / 60+ years, %), International migrant stock (000/% of total pop.), Refugees and others of concern to UNHCR (in thousands), Infant mortality rate (per 1000 live births, Health: Total expenditure (% of GDP), Health: Physicians (per 1000 pop.), Education: Government expenditure (% of GDP), Education: Primary gross enrol. ratio (f/m per 100 pop.), Education: Secondary gross enrol. ratio (f/m per 100 pop.), Education: Tertiary gross enrol. ratio (f/m per 100 pop.), Seats held by women in national parliaments %, Mobile-cellular subscriptions (per 100 inhabitants), Mobile-cellular subscriptions (per 100 inhabitants).1, Individuals using the Internet (per 100 inhabitants), Threatened species (number), Forested area (% of land area), CO2 emission estimates (million tons/tons per capita), Energy production, primary (Petajoules), Energy supply per capita (Gigajoules), Pop. using improved drinking water (urban/rural, %), Pop. using improved sanitation facilities (urban/rural, %), Net Official Development Assist. received (% of GNI)]
Index: []

[0 rows x 50 columns]

In [18]:
#check for Russia
df_renamed[df_renamed['Country'].str.contains("RUSSIA")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
167,RUSSIANFEDERATION,EasternEurope,17098246,143990,8.8,86.8,1326016,-3.7,9243.3,4.7,...,73.4,235,49.8,1705.3/11.9,54829,208,98.9/91.2,77.0/58.7,-99,-99

In [19]:
#Change to Russia in both sets
df_renamed['Country'] = df_renamed['Country'].replace(['RUSSIANFEDERATION'], ['RUSSIA'])

In [20]:
#Check South Korea
df_renamed[df_renamed['Country'].str.contains("KOREA")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
55,DEMOCRATICPEOPLE'SREPUBLICOFKOREA,EasternAsia,120538,25491,211.7,95.7,16283,-1.1,648.0,21.6,...,0,78,42.8,40.5/1.6,871,20,99.9/99.4,87.9/72.5,-99,-99
164,REPUBLICOFKOREA,EasternAsia,100284,50982,524.3,100.2,1377873,2.6,27396.7,2.3,...,89.9,111,63.5,587.2/11.7,2023,223,99.7/87.9,100.0/100.0,-99,-99

In [21]:
#CHANGE TO SOUTH KOREA
df_renamed['Country'] = df_renamed['Country'].replace(['REPUBLICOFKOREA'], ['SOUTHKOREA'])

In [22]:
#check Moldova
df_renamed[df_renamed['Country'].str.contains("MOLD")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
165,REPUBLICOFMOLDOVA,EasternEurope,33846,4051,123.3,92.2,6475,-0.7,1591.4,13.4,...,49.8,35,12.3,4.9/1.2,15,23,96.9/81.4,87.8/67.1,4.49,-99

In [23]:
#CHANGE TO MOLDOVA
df_renamed['Country'] = df_renamed['Country'].replace(['REPUBLICOFMOLDOVA'], ['MOLDOVA'])

In [24]:
#check Bolivia
df_renamed[df_renamed['Country'].str.contains("BOL")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
24,BOLIVIA(PLURINATIONALSTATEOF),SouthAmerica,1098581,11052,10.2,100.2,32998,4.8,3076.8,12.6,...,45.1,231,50.8,20.4/1.9,962,32,96.7/75.6,60.8/27.5,2.38,-99
222,VENEZUELA(BOLIVARIANREPUBLICOF),SouthAmerica,912050,31977,36.3,99.0,344331,-6.2,11068.9,5.3,...,61.9,328,53.1,185.2/6.1,7460,90,95.0/77.9,97.5/69.9,0.01,-99

In [25]:
#CHANGE BOLIVIA
df_renamed['Country']= df_renamed['Country'].replace(['BOLIVIA(PLURINATIONALSTATEOF)'], ['BOLIVIA'])

In [26]:
#Cyprus is combined in one dataset and not in the other, in order to keep data accurate Cyprus will be dropped
df_renamed[df_renamed['Country'].str.contains("CYPRUS")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
53,CYPRUS,WesternAsia,9251,1180,127.7,100.2,19561,1.7,21941.9,2.3,...,71.7,72,18.7,6.1/5.2,5,72,100.0/100.0,100.0/100.0,-99,-99

In [27]:
#Hong Kong
df_renamed[df_renamed['Country'].str.contains("HONG")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
43,"CHINA,HONGKONGSAR",EasternAsia,1106,7365,7014.2,85.1,309236,2.4,42431.0,0.1,...,84.9,64,-99,46.2/6.4,-99,83,-99,-99,-99,-99

In [28]:
#Hong Kong change
df_renamed['Country']=df_renamed['Country'].replace(['CHINA,HONGKONGSAR'], ['HONGKONGS.A.R.,CHINA'])

In [29]:
#Kosovo not included, partially recognised so missing
df_renamed[df_renamed['Country'].str.contains("KOSOVO")]

Empty DataFrame
Columns: [Country, Region, Surface area (km2), Population in thousands (2017), Population density (per km2, 2017), Sex ratio (m per 100 f, 2017), GDP: Gross domestic product (million current US$), GDP growth rate (annual %, const. 2005 prices), GDP per capita (current US$), Economy: Agriculture (% of GVA), Economy: Industry (% of GVA), Economy: Services and other activity (% of GVA), Employment: Agriculture (% of employed), Employment: Industry (% of employed), Employment: Services (% of employed), Unemployment (% of labour force), Labour force participation (female/male pop. %), Agricultural production index (2004-2006=100), Food production index (2004-2006=100), International trade: Exports (million US$), International trade: Imports (million US$), International trade: Balance (million US$), Balance of payments, current account (million US$), Population growth rate (average annual %), Urban population (% of total population), Urban population growth rate (average annual %), Fertility rate, total (live births per woman), Life expectancy at birth (females/males, years), Population age distribution (0-14 / 60+ years, %), International migrant stock (000/% of total pop.), Refugees and others of concern to UNHCR (in thousands), Infant mortality rate (per 1000 live births, Health: Total expenditure (% of GDP), Health: Physicians (per 1000 pop.), Education: Government expenditure (% of GDP), Education: Primary gross enrol. ratio (f/m per 100 pop.), Education: Secondary gross enrol. ratio (f/m per 100 pop.), Education: Tertiary gross enrol. ratio (f/m per 100 pop.), Seats held by women in national parliaments %, Mobile-cellular subscriptions (per 100 inhabitants), Mobile-cellular subscriptions (per 100 inhabitants).1, Individuals using the Internet (per 100 inhabitants), Threatened species (number), Forested area (% of land area), CO2 emission estimates (million tons/tons per capita), Energy production, primary (Petajoules), Energy supply per capita (Gigajoules), Pop. using improved drinking water (urban/rural, %), Pop. using improved sanitation facilities (urban/rural, %), Net Official Development Assist. received (% of GNI)]
Index: []

[0 rows x 50 columns]

In [30]:
#VENEZUELA
df_renamed[df_renamed['Country'].str.contains("VENEZ")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
222,VENEZUELA(BOLIVARIANREPUBLICOF),SouthAmerica,912050,31977,36.3,99.0,344331,-6.2,11068.9,5.3,...,61.9,328,53.1,185.2/6.1,7460,90,95.0/77.9,97.5/69.9,0.01,-99

In [31]:
#Venezuela change
df_renamed['Country']=df_renamed['Country'].replace(['VENEZUELA(BOLIVARIANREPUBLICOF)'], ['VENEZUELA'])

In [32]:
#Macedonia
df_renamed[df_renamed['Country'].str.contains("MACEDONIA")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
201,THEFORMERYUGOSLAVREPUBLICOFMACEDONIA,SouthernEurope,25713,2083,82.6,100.0,10052,3.8,4836.1,12,...,70.4,110,39.6,7.5/3.6,53,53,99.8/98.9,97.2/82.6,2.18,-99

In [33]:
#Macedonia change
df_renamed['Country']=df_renamed['Country'].replace(['THEFORMERYUGOSLAVREPUBLICOFMACEDONIA'], ['MACEDONIA'])

In [34]:
#Palestinian Territories
df_renamed[df_renamed['Country'].str.contains("PALES")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
192,STATEOFPALESTINE,WesternAsia,6020,4921,817.4,102.9,12677,3.5,2715.5,4.8,...,57.4,31,1.5,2.8/0.6,9,15,50.7/81.5,93.0/90.2,17.52,-99

In [35]:
#Palestine change
df_renamed['Country']=df_renamed['Country'].replace(['STATEOFPALESTINE'], ['PALESTINIANTERRITORIES'])

In [36]:
#Search Iran
df_renamed[df_renamed['Country'].str.contains("IRAN")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
97,IRAN(ISLAMICREPUBLICOF),SouthernAsia,1628750,81163,49.8,101.2,398563,0.4,5038.1,8.6,...,44.1,134,6.6,649.5/8.3,13291,127,97.7/92.1,92.8/82.3,0.02,-99

In [37]:
#Change Iran
df_renamed['Country']=df_renamed['Country'].replace(['IRAN(ISLAMICREPUBLICOF)'], ['IRAN'])

In [38]:
#Congo
df_renamed[df_renamed['Country'].str.contains("CONGO")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
48,CONGO,MiddleAfrica,342000,5261,15.4,100.1,8493,1.2,1838.1,4.7,...,7.6,134,65.4,3.1/0.7,648,24,95.8/40.0,20.0/5.6,1.05,-99
56,DEMOCRATICREPUBLICOFTHECONGO,MiddleAfrica,2344858,81340,35.9,99.6,37569,7,486.2,19.9,...,3.8,349,67.4,4.7/0.1,1179,16,81.1/31.2,28.5/28.7,8.01,-99

In [39]:
#rename both based on capital
df_renamed['Country']=df_renamed['Country'].replace(['CONGO'], ['CONGO(BRAZZAVILLE)'])
df_renamed['Country']=df_renamed['Country'].replace(['DEMOCRATICREPUBLICOFTHECONGO'], ['CONGO(KINSHASA)'])

In [40]:
#Ivory Coast does not seem to appear in dataset, also tried under alternative Côte d'Ivoire
df_renamed[df_renamed['Country'].str.contains("IVORY")]

Empty DataFrame
Columns: [Country, Region, Surface area (km2), Population in thousands (2017), Population density (per km2, 2017), Sex ratio (m per 100 f, 2017), GDP: Gross domestic product (million current US$), GDP growth rate (annual %, const. 2005 prices), GDP per capita (current US$), Economy: Agriculture (% of GVA), Economy: Industry (% of GVA), Economy: Services and other activity (% of GVA), Employment: Agriculture (% of employed), Employment: Industry (% of employed), Employment: Services (% of employed), Unemployment (% of labour force), Labour force participation (female/male pop. %), Agricultural production index (2004-2006=100), Food production index (2004-2006=100), International trade: Exports (million US$), International trade: Imports (million US$), International trade: Balance (million US$), Balance of payments, current account (million US$), Population growth rate (average annual %), Urban population (% of total population), Urban population growth rate (average annual %), Fertility rate, total (live births per woman), Life expectancy at birth (females/males, years), Population age distribution (0-14 / 60+ years, %), International migrant stock (000/% of total pop.), Refugees and others of concern to UNHCR (in thousands), Infant mortality rate (per 1000 live births, Health: Total expenditure (% of GDP), Health: Physicians (per 1000 pop.), Education: Government expenditure (% of GDP), Education: Primary gross enrol. ratio (f/m per 100 pop.), Education: Secondary gross enrol. ratio (f/m per 100 pop.), Education: Tertiary gross enrol. ratio (f/m per 100 pop.), Seats held by women in national parliaments %, Mobile-cellular subscriptions (per 100 inhabitants), Mobile-cellular subscriptions (per 100 inhabitants).1, Individuals using the Internet (per 100 inhabitants), Threatened species (number), Forested area (% of land area), CO2 emission estimates (million tons/tons per capita), Energy production, primary (Petajoules), Energy supply per capita (Gigajoules), Pop. using improved drinking water (urban/rural, %), Pop. using improved sanitation facilities (urban/rural, %), Net Official Development Assist. received (% of GNI)]
Index: []

[0 rows x 50 columns]

In [41]:
#Syria
df_renamed[df_renamed['Country'].str.contains("SYRIA")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
198,SYRIANARABREPUBLIC,WesternAsia,185180,18270,99.5,102.1,28393,-5.3,1534.5,20.7,...,30,132,2.7,30.7/1.7,237,24,92.3/87.2,96.2/95.1,...,-99

In [42]:
#Syria change
df_renamed['Country']=df_renamed['Country'].replace(['SYRIANARABREPUBLIC'], ['SYRIA'])

In [43]:
df_renamed[df_renamed['Country'].str.contains("TANZ")]

,Country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
216,UNITEDREPUBLICOFTANZANIA,EasternAfrica,947303,57310,64.7,97.8,45628,7,877.3,31.1,...,5.4,1082,52.4,11.6/0.2,935,20,77.2/45.5,31.3/8.3,5.85,-99

In [44]:
#Tanzania change
df_renamed['Country']=df_renamed['Country'].replace(['UNITEDREPUBLICOFTANZANIA'], ['TANZANIA'])

In [45]:
#remerge after changes
df_merged=pd.merge(df, df_renamed, left_on='Country', right_on='Country')

In [46]:
df_merged.to_csv(r'C:\Users\jackm\Documents\Data Analytics\CW\2017Merge.csv', index = False)

In [47]:
#check and print null data

#outerjoin to determine missing values, only those missing or decided to drop remain
df_missing = pd.merge(df, df_renamed, on ='Country', how='left')
null_data = df_missing[df_missing.isnull().any(axis=1)]
print(null_data)
df_missing.to_csv(r'C:\Users\jackm\Documents\Data Analytics\CW\null.csv', index = False)

                   Country  Happiness.Rank  Happiness.Score  Whisker.high  \
32   TAIWANPROVINCEOFCHINA              33            6.422      6.494596
60             NORTHCYPRUS              61            5.810      5.897366
77                  KOSOVO              78            5.279      5.364848
127             IVORYCOAST             128            4.180      4.275183

     Whisker.low  Economy..GDP.per.Capita.    Family  \
32      6.349404                  1.433627  1.384565
60      5.722633                  1.346911  1.186303
77      5.193152                  0.951484  1.137854
127     4.084817                  0.603049  0.904780

     Health..Life.Expectancy.   Freedom  Generosity  ...  \
32                   0.793984  0.361467    0.258360  ...
60                   0.834647  0.471204    0.266846  ...
77                   0.541452  0.260288    0.319931  ...
127                  0.048642  0.447706    0.201237  ...

     Mobile-cellular subscriptions (per 100 inhabitants).1  \
32                                                 NaN
60                                                 NaN
77                                                 NaN
127                                                NaN

     Individuals using the Internet (per 100 inhabitants)  \
32                                                 NaN
60                                                 NaN
77                                                 NaN
127                                                NaN

    Threatened species (number) Forested area (% of land area)  \
32                          NaN                            NaN
60                          NaN                            NaN
77                          NaN                            NaN
127                         NaN                            NaN

     CO2 emission estimates (million tons/tons per capita)  \
32                                                 NaN
60                                                 NaN
77                                                 NaN
127                                                NaN

     Energy production, primary (Petajoules)  \
32                                       NaN
60                                       NaN
77                                       NaN
127                                      NaN

     Energy supply per capita (Gigajoules)  \
32                                     NaN
60                                     NaN
77                                     NaN
127                                    NaN

     Pop. using improved drinking water (urban/rural, %)  \
32                                                 NaN
60                                                 NaN
77                                                 NaN
127                                                NaN

    Pop. using improved sanitation facilities (urban/rural, %)  \
32                                                 NaN
60                                                 NaN
77                                                 NaN
127                                                NaN

     Net Official Development Assist. received (% of GNI)
32                                                 NaN
60                                                 NaN
77                                                 NaN
127                                                NaN

[4 rows x 61 columns]